spring.application.name=demoAPI
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cdapizza
spring.datasource.name=cdapizza
spring.datasource.username=cdapizza
spring.datasource.password=cdapizza
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=+CpiHt5GKMqO98Nu4ENjFNVpptH395PZKGZG8wK3hQgKGhQ5TbgvSVfz7uE1azudyqs406DAPbLGxd4hKaH3rQ==
jwt.expiration=3600000

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true