spring.application.name=demoAPI
server.port = 8080

# Bdd
spring.datasource.url=${DB_URL}
spring.datasource.name=${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# cf partie 4 pour + d'infos : https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
spring.jpa.hibernate.ddl-auto=none
# Spring exécute schema.sql + data.sql à chaque démarrage
spring.sql.init.mode=always

# data.sql s'exécute APRÈS qu'Hibernate a initialisé JPA
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
# afficher les requetes SQL dans le terminal
# https://www.baeldung.com/sql-logging-spring-boot
spring.jpa.properties.hibernate.format_sql=true
#
logging.level.net.ttddyy.dsproxy.listener=debug

# JWT TOKEN
jwt.secret=${JWT_SECRET}
# token valide 1 heure
jwt.expiration=3600000